name: HardHat CI

on:
  push:
    branches: [main]
  schedule:
  - cron: "00 06 * * 1"

jobs:
  dchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Project
        run: |
          ./install.sh
      - name: Run Project Test Suite
        run: |
          ./dryrun.sh