name: HardHat CI

on:
  push:
    branches: [main, hardhat-dev]

jobs:
  dchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Project
        run: |
          sudo ./install.sh
      - name: Run Project Test Suite
        run: |
          sudo ./dryrun.sh